version: 2
jobs:
  checkout_code:
    working_directory: ~/anotherfizz
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths: .
  unit_tests:
    working_directory: ~/anotherfizz
    docker:
      - image: circleci/python:3.6.1
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Run unittest
          command: python fizzbuzztest.py

  build_image:
    working_directory: ~/anotherfizz
    docker:
    - image: circleci/python:3.6.1
    steps:
      - setup_remote_docker
      - attach_workspace:
        at: .
      - run: 
          docker build -t dearpyn/dearfizzbuzz:2 .
          docker login -u dearpyn -p $DOCKER_PASS
          docker push dearpyn/dearfizzbuzz:2

  deploy:
    docker:
    - image: circleci/python:3.6.1
    steps:
      - checkout
      - run:
          name: Install deployment script dependencies
          command: cd ansible && pipenv install
      - run:
          name: Deploy to production
          command: cd ansible && pipenv run ansible-playbook deploy-production.yml

workflows:
  version: 2
  say-fizz-pipeline:
    jobs:
      - checkout_code
      - unit_tests:
          requires:
            - checkout_code